language: android # can be 'java' if there is no android build target
android:
  components:
    - build-tools-22.0.1
    - android-22
#    - extra-google-m2repository
#    - extra-android-m2repository
jdk: oraclejdk8

# Cache gradle dependencies (should be faster to download them from cache)
cache:
  directories:
  - $HOME/.gradle

# Setup environment
before_install:
- chmod +x gradlew
