language: java

jdk: oraclejdk8

# Cache gradle dependencies (should be faster to download them from cache)
cache:
  directories:
  - $HOME/.gradle

# Setup environment
before_install:
- chmod +x gradlew
