language: java
sudo: false #faster builds

jdk: oraclejdk8

# Cache gradle dependencies (should be faster to download them from cache)
cache:
  directories:
  - $HOME/.gradle

# Setup environment
before_install:
- chmod +x gradlew

script:
      - ./gradlew sonarqube -Dsonar.host.url=http://smartr.cs.hm.edu:9000
